plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.13'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'org.owasp.dependencycheck' version '12.2.2'
}

group = 'com.lifeforest'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.google.zxing:core:3.5.3'

    compileOnly 'org.projectlombok:lombok'
    compileOnly 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'com.h2database:h2'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy(tasks.named('jacocoTestReport'))
}

jacoco {
    toolVersion = '0.8.13'
}

tasks.named('jacocoTestReport') {
    dependsOn(tasks.named('test'))

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

tasks.register('prepareSonarLibraries', Copy) {
    from(configurations.runtimeClasspath)
    into(layout.buildDirectory.dir('sonar-libs/main'))
}

tasks.register('prepareSonarTestLibraries', Copy) {
    from(configurations.testRuntimeClasspath)
    into(layout.buildDirectory.dir('sonar-libs/test'))
}

tasks.named('bootJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencyCheck {
    failBuildOnCVSS = 7.0
    failOnError = false
    formats = ['HTML', 'JSON']
    analyzers {
        assemblyEnabled = false
    }
}
