import { StyleSheet } from 'react-native';

export const appColors = {
  screen: '#0F1B16',
  card: '#14251F',
  cardAlt: '#182D24',
  cardBorder: '#244338',
  input: '#20352D',
  inputBorder: '#355648',
  inputText: '#FFFFFF',
  text: '#EAF6F0',
  mutedText: '#B7CCC2',
  subtleText: '#98B7A7',
  softText: '#A7C8B7',
  primary: '#7EE081',
  primaryBorder: '#A5F0AF',
  primaryText: '#102218',
  secondary: '#1D3A2E',
  secondaryBorder: '#4FAF7A',
  secondaryText: '#F3FBF6',
  ghost: '#162B22',
  ghostBorder: '#547568',
  ghostText: '#F0F8F3',
  error: '#FF8A8A',
  errorSurface: '#2A1717',
  errorBorder: '#6D2B2B',
  errorTextStrong: '#FFD9D9',
  errorTextSoft: '#FFB6B6',
  success: '#7EE081',
  danger: '#B94A4A',
  dangerBorder: '#E28787',
  dangerText: '#FFFFFF',
  warningSurface: '#3D2718',
  warningBorder: '#F2C66D',
  warningText: '#F2C66D',
  bluePanel: '#233140',
  blueBorder: '#88B8FF',
  blueText: '#B4D4FF',
  greenPanel: '#183524',
  greenText: '#8DE2A8',
  panel: '#1A2D26',
  panelSoft: '#172923',
  panelStrong: '#20362C',
  panelBorder: '#2B4A3E',
  selectedPanel: '#234233',
  selectedPanelBorder: '#63C174',
  progressTrack: '#21392F',
  progressTrackBorder: '#305446',
  accentBlue: '#9EDCFF',
  accentGold: '#F1C96B',
  accentAmber: '#E9B97A',
  accentPink: '#F2A8FF',
  placeholder: '#7A7A7A',
} as const;

export const appSharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: appColors.screen,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: 24,
    paddingBottom: 72,
  },
  card: {
    width: '100%',
    alignSelf: 'center',
    borderRadius: 24,
    padding: 24,
    backgroundColor: appColors.card,
    borderWidth: 1,
    borderColor: appColors.cardBorder,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  title: {
    color: appColors.text,
    marginBottom: 8,
  },
  subtitle: {
    color: appColors.mutedText,
    marginBottom: 20,
  },
  form: {
    gap: 14,
  },
  input: {
    backgroundColor: appColors.input,
    color: appColors.inputText,
    borderWidth: 1,
    borderColor: appColors.inputBorder,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  helperText: {
    color: appColors.subtleText,
  },
  errorText: {
    color: appColors.error,
    marginTop: 8,
  },
  successText: {
    color: appColors.success,
    marginTop: 8,
  },
});
